// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.4
// source: class_registration_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClassRegistrationStatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClassIds []int32 `protobuf:"varint,1,rep,packed,name=classIds,proto3" json:"classIds,omitempty"`
}

func (x *ClassRegistrationStatRequest) Reset() {
	*x = ClassRegistrationStatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_class_registration_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClassRegistrationStatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassRegistrationStatRequest) ProtoMessage() {}

func (x *ClassRegistrationStatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_class_registration_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassRegistrationStatRequest.ProtoReflect.Descriptor instead.
func (*ClassRegistrationStatRequest) Descriptor() ([]byte, []int) {
	return file_class_registration_service_proto_rawDescGZIP(), []int{0}
}

func (x *ClassRegistrationStatRequest) GetClassIds() []int32 {
	if x != nil {
		return x.ClassIds
	}
	return nil
}

type ClassRegistrationStatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result map[int32]int32 `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *ClassRegistrationStatResponse) Reset() {
	*x = ClassRegistrationStatResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_class_registration_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClassRegistrationStatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassRegistrationStatResponse) ProtoMessage() {}

func (x *ClassRegistrationStatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_class_registration_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassRegistrationStatResponse.ProtoReflect.Descriptor instead.
func (*ClassRegistrationStatResponse) Descriptor() ([]byte, []int) {
	return file_class_registration_service_proto_rawDescGZIP(), []int{1}
}

func (x *ClassRegistrationStatResponse) GetResult() map[int32]int32 {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_class_registration_service_proto protoreflect.FileDescriptor

var file_class_registration_service_proto_rawDesc = []byte{
	0x0a, 0x20, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x5f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x04, 0x64, 0x65, 0x6d, 0x6f, 0x22, 0x3a, 0x0a, 0x1c, 0x43, 0x6c, 0x61, 0x73,
	0x73, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6c, 0x61, 0x73,
	0x73, 0x49, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x08, 0x63, 0x6c, 0x61, 0x73,
	0x73, 0x49, 0x64, 0x73, 0x22, 0xa3, 0x01, 0x0a, 0x1d, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x43, 0x6c,
	0x61, 0x73, 0x73, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53,
	0x74, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x1a,
	0x39, 0x0a, 0x0b, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x32, 0x81, 0x01, 0x0a, 0x18, 0x43,
	0x6c, 0x61, 0x73, 0x73, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x65, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x43, 0x6c,
	0x61, 0x73, 0x73, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53,
	0x74, 0x61, 0x74, 0x12, 0x22, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x43, 0x6c, 0x61, 0x73, 0x73,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x43,
	0x6c, 0x61, 0x73, 0x73, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x53, 0x74, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x08,
	0x5a, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_class_registration_service_proto_rawDescOnce sync.Once
	file_class_registration_service_proto_rawDescData = file_class_registration_service_proto_rawDesc
)

func file_class_registration_service_proto_rawDescGZIP() []byte {
	file_class_registration_service_proto_rawDescOnce.Do(func() {
		file_class_registration_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_class_registration_service_proto_rawDescData)
	})
	return file_class_registration_service_proto_rawDescData
}

var file_class_registration_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_class_registration_service_proto_goTypes = []interface{}{
	(*ClassRegistrationStatRequest)(nil),  // 0: demo.ClassRegistrationStatRequest
	(*ClassRegistrationStatResponse)(nil), // 1: demo.ClassRegistrationStatResponse
	nil,                                   // 2: demo.ClassRegistrationStatResponse.ResultEntry
}
var file_class_registration_service_proto_depIdxs = []int32{
	2, // 0: demo.ClassRegistrationStatResponse.result:type_name -> demo.ClassRegistrationStatResponse.ResultEntry
	0, // 1: demo.ClassRegistrationService.GetClassRegistrationStat:input_type -> demo.ClassRegistrationStatRequest
	1, // 2: demo.ClassRegistrationService.GetClassRegistrationStat:output_type -> demo.ClassRegistrationStatResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_class_registration_service_proto_init() }
func file_class_registration_service_proto_init() {
	if File_class_registration_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_class_registration_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClassRegistrationStatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_class_registration_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClassRegistrationStatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_class_registration_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_class_registration_service_proto_goTypes,
		DependencyIndexes: file_class_registration_service_proto_depIdxs,
		MessageInfos:      file_class_registration_service_proto_msgTypes,
	}.Build()
	File_class_registration_service_proto = out.File
	file_class_registration_service_proto_rawDesc = nil
	file_class_registration_service_proto_goTypes = nil
	file_class_registration_service_proto_depIdxs = nil
}
